services:
  consul:
    image: hashicorp/consul:1.16
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - banknet
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost:8500/v1/status/leader" ]
      interval: 2s
      timeout: 1s
      retries: 30

  kv-seeder:
    image: alpine:3.20
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - banknet
    volumes:
      - ./consul/kv/application.properties:/seed/application.properties:ro
      - ./consul/kv/seed-kv.sh:/seed/seed-kv.sh:ro
    entrypoint: /bin/sh -c "apk add --no-cache curl >/dev/null && /bin/sh /seed/seed-kv.sh"
    restart: "no"

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=bank
      - POSTGRES_PASSWORD=bank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banknet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8089:8080"
    depends_on:
      - postgres
    networks:
      - banknet

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    ports:
      - "8084:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    depends_on:
      - postgres
    networks:
      - banknet

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
      args:
        MODULE: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - front-ui
      - exchange
    networks:
      - banknet

  front-ui:
    build:
      context: .
      dockerfile: front-ui/Dockerfile
      args:
        MODULE: front-ui
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:consul:consul:8500
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    expose:
      - "8081"
    ports:
      - "5005:5005"
    depends_on:
      - consul
    networks:
      - banknet

  exchange:
    build:
      context: .
      dockerfile: exchange/Dockerfile
      args:
        MODULE: exchange
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8082"
    depends_on:
      - consul
      - postgres
    networks:
      - banknet

  exchange-generator:
    build:
      context: .
      dockerfile: exchange-generator/Dockerfile
      args:
        MODULE: exchange-generator
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - consul
      - exchange
    networks:
      - banknet

  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
      args:
        MODULE: accounts
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
    expose:
      - "8084"
    ports:
      - "5008:5008"
    depends_on:
      - consul
      - postgres
    networks:
      - banknet

  cash:
    build:
      context: .
      dockerfile: cash/Dockerfile
      args:
        MODULE: cash
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:consul:consul:8500
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
    expose:
      - "8085"
    ports:
      - "5007:5007"
    depends_on:
      - consul
      - accounts
    networks:
      - banknet

  blocker:
    build:
      context: .
      dockerfile: blocker/Dockerfile
      args:
        MODULE: blocker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8086"
    depends_on:
      - consul
    networks:
      - banknet

  transfer:
    build:
      context: .
      dockerfile: transfer/Dockerfile
      args:
        MODULE: transfer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:consul:consul:8500
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    expose:
      - "8087"
    ports:
      - "5006:5006"
    depends_on:
      - consul
      - accounts
      - exchange
      - blocker
    networks:
      - banknet

  notifications:
    build:
      context: .
      dockerfile: notifications/Dockerfile
      args:
        MODULE: notifications
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8088"
    depends_on:
      - consul
    networks:
      - banknet

networks:
  banknet:
    driver: bridge

volumes:
  pgdata:

#debug
# - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
# ports:
#  - "5005:5005"