services:
  consul:
    image: hashicorp/consul:1.16
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - banknet

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=bank
      - POSTGRES_PASSWORD=bank
    ports:
      - "5432:5432"
    networks:
      - banknet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8089:8080"
    depends_on:
      - postgres
    networks:
      - banknet

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    ports:
      - "8084:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    depends_on:
      - postgres
    networks:
      - banknet

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
      args:
        MODULE: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - front-ui
      - exchange
    networks:
      - banknet

  front-ui:
    build:
      context: .
      dockerfile: front-ui/Dockerfile
      args:
        MODULE: front-ui
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    expose:
      - "8081"
    ports:
      - "5005:5005"
    depends_on:
      - consul
    networks:
      - banknet

  exchange:
    build:
      context: .
      dockerfile: exchange/Dockerfile
      args:
        MODULE: exchange
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8082"
    depends_on:
      - consul
      - postgres
    networks:
      - banknet

  exchange-generator:
    build:
      context: .
      dockerfile: exchange-generator/Dockerfile
      args:
        MODULE: exchange-generator
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - consul
      - exchange
    networks:
      - banknet

  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
      args:
        MODULE: accounts
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8084"
    depends_on:
      - consul
      - postgres
    networks:
      - banknet

networks:
  banknet:
    driver: bridge

#debug
# - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
# ports:
#  - "5005:5005"