server:
  port: 8087

spring:
  application:
    name: transfer
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
  security:
    oauth2:
      client:
        registration:
          transfer:
            provider: keycloak
            client-id: transfer
            client-secret: transfer-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/bank/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG