server:
  port: 8087

spring:
  application:
    name: transfer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
  security:
    oauth2:
      client:
        registration:
          transfer:
            provider: keycloak
            client-id: transfer
            client-secret: transfer-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8084/realms/bank/protocol/openid-connect/token

resilience4j:
  retry:
    instances:
      s2s:
        maxAttempts: 3
        waitDuration: 200ms
  circuitbreaker:
    instances:
      s2s:
        slidingWindowSize: 20
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG