server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
    gateway:
      server:
        webflux:
          routes:
            - id: api-rates
              uri: lb://exchange
              predicates:
                - Path=/api/rates
            - id: accounts-api
              uri: lb://accounts
              predicates:
                - Path=/api/users, /api/users/*, /api/internal/**
            - id: front-ui
              uri: lb://front-ui
              predicates:
                - Path=/**
          default-filters:
            - PreserveHostHeader

management:
  endpoints:
    web:
      exposure:
        include: health,info
