server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
    gateway:
      server:
        webflux:
          routes:
            - id: api-rates
              uri: lb://exchange
              predicates:
                - Path=/api/rates
            - id: front-ui
              uri: lb://front-ui
              predicates:
                - Path=/**
          default-filters:
            - PreserveHostHeader
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
