server:
  port: 8085

spring:
  application:
    name: cash
  config:
    import: optional:consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
      config:
        enabled: true
        format: properties
        prefixes: config
        defaultContext: application
        data-key: data
  security:
    oauth2:
      client:
        registration:
          cash:
            provider: keycloak
            client-id: cash
            client-secret: cash-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8084/realms/bank/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG