server:
  port: 8084

spring:
  application:
    name: accounts
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/bank
  datasource:
    url: jdbc:postgresql://localhost:5432/bank?currentSchema=accounts
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: accounts
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: accounts
    schemas: accounts
    table: flyway_schema_history_accounts

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
