server:
  port: 8081

spring:
  application:
    name: front-ui
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
  security:
    oauth2:
      client:
        registration:
          front-ui:
            provider: keycloak
            client-id: front-ui
            client-secret: front-ui-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/bank/protocol/openid-connect/token
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

resilience4j:
  retry:
    instances:
      s2s:
        maxAttempts: 3
        waitDuration: 200ms
  circuitbreaker:
    instances:
      s2s:
        slidingWindowSize: 20
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG