server:
  port: 8081

spring:
  application:
    name: front-ui
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration