server:
  port: 8083

spring:
  application:
    name: exchange-generator
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
  security:
    oauth2:
      client:
        registration:
          exchange-generator:
            provider: keycloak
            client-id: exchange-generator
            client-secret: gen-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/bank/protocol/openid-connect/token
  thymeleaf:
    check-template-location: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,scheduledtasks,metrics

resilience4j:
  retry:
    instances:
      push:
        maxAttempts: 3
        waitDuration: 200ms
logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
