server:
  port: 8088

spring:
  application:
    name: notifications
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG