server:
  port: 8082

spring:
  application:
    name: exchange
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank
  datasource:
    url: jdbc:postgresql://postgres:5432/bank?currentSchema=exchange
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: exchange
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: exchange
    schemas: exchange
    table: flyway_schema_history_exchange

management:
  endpoints:
    web:
      exposure:
        include: health,info
