server:
  port: 8082

spring:
  application:
    name: exchange
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
  datasource:
    url: jdbc:postgresql://postgres:5432/bank
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
